version: 0.2

phases:
  install:
    commands:
      - echo "Nothing to install for a static website"
  build:
    commands:
      - echo "No build commands needed for static files"
  post_build:
    commands:
      - echo "Deploying to S3..."
      - aws s3 sync ./ s3://my-static-website-bucket/ --delete

artifacts:
  files:
    - '**/*'
