version: 0.2

phases:
  install:
    commands:
      - echo "Nothing to install for a static website"
  build:
    commands:
      - echo "No build commands needed for static files"
  post_build:
    commands:
      - echo "Preparing files for deployment"
artifacts:
  files:
    - '**/*'  
